### ISSUE TITLE
buildTokenizeRequestSchema

### ISSUE THREAD

**Issue by mery8** [Mastercard/mastercard-api-client-tutorial#19]
hello,
while i'm testing i get this error message : The method buildTokenizeRequestSchema() is undefined 
in this line :
TokenizeRequestSchema request = buildTokenizeRequestSchema();

help plz

**Comment by ech0s7r** [comment]
Hi @mery8,

Could you please provide the steps for reproducing the behavior? 

If you are testing the Java client, please ensure you have replaced the [dummy values](https://github.com/Mastercard/mastercard-api-client-tutorial/blob/master/java/src/test/java/com/mastercard/developer/mdes_digital_enablement_client/api/TokenizeApiTest.java#L28-L31) in the `TokenizeApiTest` class with valid credentials and you ran `mvn clean install` in the `java` folder to build and execute the tests. 

You might find useful this [tutorial](https://developer.mastercard.com/platform/documentation/security-and-authentication/generating-and-configuring-a-mastercard-api-client/). It will walk you through the steps to generate a configure a Mastercard API Client in multiple languages.

**Comment by jaaufauvre** [comment]
Ticket closed due to inactivity. Please reopen it if needed.
