### ISSUE TITLE
tokenizeResponseSchema null 

### ISSUE THREAD

**Issue by ileen01** [Mastercard/mastercard-api-client-tutorial#20]
hello,
i'am working on tokenization project,i'am using tokenizeApi but when i send a tokenization request i get null response( all fields are null) 
i don't know what is the problem.
help please

**Comment by jaaufauvre** [comment]
Hi @ileen01, unless you can share a project for us to reproduce the behaviour you describe (without your keys and sensitive information), please reach out to the Mastercard support team. For that, see: https://developer.mastercard.com/support/.

**Comment by jaaufauvre** [comment]
Hi @ileen01, I just updated the Java and C# projects to use:
- The latest MDES Digital Enablement specification (v1.3.0)
- OpenAPI Generator 5.1.1
- The latest version of Mastercard client libraries

Can you please check again?

**Comment by jaaufauvre** [comment]
Issue closed due to inactivity. Please reopen it if needed.

**Comment by sajasbana** [comment]
Dears
I have the same issue
I followed this tutorial https://developer.mastercard.com/mdes-digital-enablement/documentation/tutorials/create-a-new-project/#6-download-client-encryption-key-sandbox

I download this github project for c#

I modified the specified fields in the doc link

but when running the test, we get all fields null, except responseId
