### ISSUE TITLE
Unable to open charp project

### ISSUE THREAD

**Issue by rukish** [Mastercard/mastercard-api-client-tutorial#23]
I am unable to open the csharp project in VS2015 

The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  E:\MasterCard\mastercard-api-client-tutorial-main\csharp\Acme.App.MastercardApi.Client\Acme.App.MastercardApi.Client.csproj

 The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  E:\MasterCard\mastercard-api-client-tutorial-main\csharp\Acme.App.MastercardApi.Client.Tests\Acme.App.MastercardApi.Client.Tests.csproj

**Comment by jaaufauvre** [comment]
Hi @rukish, the solution file can be opened with Visual Studio Code, Visual Studio 2019+ or JetBrains Rider for instance.

**Comment by rukish** [comment]
Thanks for the prompt reply.I tried opening the solution with Visual Studio Code. It just opens the solution file in text mode .. 
I would appreciate if you could reply with the solution.
Also I would like to ask my doubt. I am downloading this project to implement the Mastercard STP integration using C#.
Could you please confirm if I am looking into the right project.

ThanksRukhiya 




regards Rukhiya 

    On Tuesday, September 28, 2021, 05:06:57 PM GMT+4, Jean-Alexis Aufauvre ***@***.***> wrote:  
 
 


Hi @rukish, the solution file can be opened with Visual Studio Code, Visual Studio 2019+ or JetBrains Rider for instance.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jaaufauvre** [comment]
You probably need an extension, like C# for Visual Studio Code.

Yes, this tutorial should work with Mastercard STP too.

**Comment by rukish** [comment]
Hi Jean
I did install C# extension for Visual Studio Code
I think I was trying to open the solution file directly. I relaized we need to open the project folder.
Is this project environment .Net Core or .Net?
Also I am not able to understand how do I test the working of client API.

I am completely new to this environment. So please ignore if I have asked any silly questions :-)


ThanksRukhiya 

    On Tuesday, September 28, 2021, 05:34:36 PM GMT+4, Jean-Alexis Aufauvre ***@***.***> wrote:  
 
 


You probably need an extension, like C# for Visual Studio Code.

Yes, this tutorial should work with Mastercard STP too.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jaaufauvre** [comment]
Hi @rukish, here is the link to the official support page: https://developer.mastercard.com/support/
