### ISSUE TITLE
Api-Client

### ISSUE THREAD

**Issue by rukish** [Mastercard/mastercard-api-client-tutorial#26]
After executing the below line  api-client folder is created.
openapi-generator-cli generate -g csharp-netcore -i *.yaml -c config.json -o api_client

I have chosen CSharp but when I try to oepn the solution using VS2015 it is unable to load the project.

Which tool is needed to open the api-client project?

**Comment by jaaufauvre** [comment]
Hi @rukish, 

It depends on the `targetFramework` you defined in your `config.json` (see: https://openapi-generator.tech/docs/generators/csharp-netcore). 

For example, some IDEs or OSes may not support the legacy .NET Framework. Or old versions of IDEs may not support .NET 5.0.

Please refer to https://github.com/Mastercard/mastercard-api-client-tutorial/issues/23#issuecomment-929191664 for the IDEs I've personally used with this project.
