### ISSUE TITLE
Failed asserting that null matches expected 'APPROVED'.

### ISSUE THREAD

**Issue by ratiodavinder** [Mastercard/mastercard-api-client-tutorial#29]
I am using PHP library for tokenization and tried to run the test case, but it is returning error message and the response does not contain any data.
I also tried the step by step guide (https://developer.mastercard.com/platform/documentation/security-and-authentication/generating-and-configuring-a-mastercard-api-client/#step-by-step-guide) and that is also returning the same result. Please see the attached screenshot for reference.

![image](https://user-images.githubusercontent.com/34365866/153365662-58e0ca21-e7e0-45fd-b943-0922e5f921f6.png)
![image](https://user-images.githubusercontent.com/34365866/153365772-85afeb1f-d1d1-469a-a38b-7aaedbdb0f3c.png)

**Comment by Akshaykdubey** [comment]
Hi @ratiodavinder 
Thanks for raising the issue.
I tried reproducing the issue but the tests works fine. We are asserting the values of `Decision` and `PaymentAccountReference` in the test and the response have both the values.
Pasting snippets of the response:
```   
["response_host"]=>
    string(36) "site.1.sample.service.mastercard.com"
    ["response_id"]=>
    string(6) "123456"
    ["decision"]=>
    string(8) "APPROVED"
    ["authentication_methods"]=>
```
```
     object(DigitalEnablementClient\Model\TokenDetailData)#66 (1) {
          ["container":protected]=>
          array(1) {
            ["payment_account_reference"]=>
            string(29) "500181d9f8e0629211e3949a08002"
          }
```

Let us know if you can provide the exact the steps to reproduce. Also the version of php you are using.

Thanks!

**Comment by ratiodavinder** [comment]
Hello Akshay,

Thanks for your response.

If we talk about the GitHub repo specifically, I followed the below steps 

- Downloaded the code from GitHub
- Added ConsumerKey, SigningKeyAlias, SigningKeyPassword, SigningKeyPkcs12FilePath in /mastercard-latest/test/Api/TokenizeApiTest.php file
- Downloaded encryption and decryption keys from https://developer.mastercard.com/mdes-digital-enablement/documentation/tutorials/create-a-new-project/#6-download-client-encryption-key-sandbox
- Added encryption and decryption file path in EncryptionCertificateFilePath and DecryptionKeyFilePath respectively.
- Used phpunit command to run /mastercard-latest/test/Api/TokenizeApiTest.php 

I also tried to add 'tokenization_authentication_value' in TokenizeRequestSchema, but didn't get any success.

I am using PHP 7.4, please let me know if I am missing something.

Thanks,
Davinder

**Comment by ratiodavinder** [comment]
Hello Akshay,

Please let me know if there is any update.

Regards,
Davinder

**Comment by Akshaykdubey** [comment]
Hi Davinder,
Can you confirm if you are using the encrypt and decrypt cert/key provided in the document of the API?

**Comment by Akshaykdubey** [comment]
Hi @ratiodavinder,
The encrypt/decrypt cert/key provided in the document seems to be causing the issue. I have contacted the service team to rectify it. I will update when we have some confirmation.

Thanks!

**Comment by ratiodavinder** [comment]
Hello @Akshaykdubey,

Like I mentioned earlier, I am using the encryption certificates provided at https://developer.mastercard.com/mdes-digital-enablement/documentation/tutorials/create-a-new-project/#6-download-client-encryption-key-sandbox

Thanks

**Comment by Advancedlux** [comment]
Hello Akshaykdubey,

Have we resolved the issue with the cert/key provided in the document? What are our next steps please?

Thanks,
Travis

**Comment by Advancedlux** [comment]
Hello,
Do we have an update yet?
Thanks,
Travis

**Comment by Advancedlux** [comment]
Hello @Akshaykdubey,
It has been almost a month. May we please get an update on how to proceed?
Thanks,
Travis
