### ISSUE TITLE
Cannot require 'mdes_for_merchants'

### ISSUE THREAD

**Issue by ImadBahsoun** [Mastercard/mastercard-api-client-tutorial#5]
var MdesForMerchants = require('mdes_for_merchants');

cannot find module mdes_for_merchants, please how can i solve this issue ?

**Comment by jaaufauvre** [comment]
Hi @ImadBahsoun, is this still an issue on your side?

**Comment by jaaufauvre** [comment]
Issue closed due to inactivity. Please reopen it if needed.
